iglu-baseline:
    env: IGLUSilentBuilder-v0
    run: IMPALA
    stop:
        timesteps_total: 100000000
    checkpoint_at_end: True
    checkpoint_freq: 10 # roughly each 50k steps
    config:
        env_config: 
          action_space: human-level
          visual: true
          size_reward: true
          # possible values are: 'one_task', 'many_tasks', 'random_tasks'
          task_mode: one_task 
          # if task_mode is one_task -> string with task id
          # if task_mode is many_tasks -> list of task ids
          # if task_mode is random_tasks -> ignored
          task_id: C32
          # only used if task_mode is random_tasks
        model:
          custom_model: pov_baseline_model
          use_lstm: True
        framework: torch
        vtrace: True
        rollout_fragment_length: 20
        train_batch_size: 500
        num_workers: 20
        num_gpus: 1
        broadcast_interval: 1
        max_sample_requests_in_flight_per_worker: 2 
        num_multi_gpu_tower_stacks: 5
        num_envs_per_worker: 1
        replay_proportion: 3.0
        replay_buffer_num_slots: 100
        learner_queue_timeout: 1000
        minibatch_buffer_size: 1
        num_sgd_iter: 1
        lr_schedule: [
            [0, 0.0005],
            [150000000, 0.000001],
        ]
        vf_loss_coeff: 0.5
        entropy_coeff: 0.01
        grad_clip: 100.0
        evaluation_num_workers: 1
        evaluation_interval: 10
        evaluation_num_episodes: 1
        evaluation_config:
          input: sampler
          explore: false